## Kiểu dữ liệu

Kiểu dữ liệu là một khái niệm rất quan trọng trong lập trình. Các biến có thể lưu trữ các loại dữ liệu khác nhau và mỗi  loại khác nhau có thể làm những việc khác nhau. Đối với Python, ngôn ngữ lập trình có các kiểu dữ liệu sau được tích hợp sẵn theo mặc định, cụ thể như sau:

- Text Type: str
- Numeric Types:  int, float, complex
- Boolean Type: bool
- Binary Types: bytes

Bằng việc sử dụng hàm `type()` , bạn có thể lấy bất kỳ kiểu dữ liệu nào của các đối tượng. Ví dụ:

```python
x = 5
print(type(x))
```

```{.python_output}
<class 'int'>
```

### Các kiểu dữ liệu số (numeric) trong Python

Python hỗ trợ các kiểu dữ liệu số Integer (số nguyên), Float (số thực) và Complex (số phức). Python định nghĩa các lớp là int, float và complex để lưu trữ và thao tác các kiểu dữ liệu số.

- Integer (số nguyên): viết tắt là `int`, là các số nguyên dương hoặc âm (không có phần phân số). Trong Python, số nguyên không có giới hạn độ dài. Ví dụ

```python
x = 1
y = 10
z = -10
```

- Float (số thực): biểu diễn bởi lớp `float`. Lớp này đại diện cho các số thực sử dụng dấu phẩy động (15 chữ số chính xác sau dấu thập phân). Các số thực có thể được biểu diễn bằng các ký hiệu e hoặc E, ký hiệu khoa học cho a10b

```python
x = 3.14
print(x)
y = 3E4
print(y)
print(type(y))
```

```{.python_output}
3.14
30000.0
<class 'float'>
```

- Complex (số phức): biểu diễn bởi lớp phức. Một số phức được viết dưới dạng `x + yj`. trong đó `x, y` là phần thực và `j` là phần ảo.

```python
x = 3 + 5j
y = 5j
print(x)
print(x+y)
```

```{.python_output}
(3+5j)
(3+10j)
```

Python thường làm việc với số trong cơ số 10. Để làm việc với cơ số khác ta sử dụng các tiền tố sau

- Hệ nhị phân : '0b' hoặc '0B'
- Hệ bát phân : '0o' hoặc '0O'
- Hệ thập lục phân '0x' hoặc '0X'

```python
a = 'Ob10101'
print(a)
```

```{.python_output}
Ob10101
```

### Kiểu dữ liệu chuỗi ký tự (string) trong Python

Các kiểu dữ liệu chuỗi trong Python được đặt trong dấu ngoặc kép đơn hoặc ngoặc kép. Python sẽ coi các lệnh trích dẫn đơn và kép như nhau, ví dụ như `"Hello"` tương đương với `'Hello'`

Gán chuỗi cho một biến

```python
name = "Phạm Xuân Bách"
print(name)
```

```{.python_output}
Phạm Xuân Bách
```

Chúng ta có thể khai báo chuỗi bằng nhiều dòng khác nhau, dùng ba dấu nháy kép hoặc ba dấu nháy đơn

```python
str1 = """Hôm nay trời nắng chang chang
mèo con đi học chẳng mang thứ gì
chỉ mang một chiếc bút chì.
Và mang một mẩu bánh mì con con
"""
print(str1)
```

```{.python_output}
Hôm nay trời nắng chang chang
mèo con đi học chẳng mang thứ gì
chỉ mang một chiếc bút chì.
Và mang một mẩu bánh mì con con
```

```python
str2 = '''Hôm nay trời nắng chang chang
mèo con đi học chẳng mang thứ gì
chỉ mang một chiếc bút chì.
Và mang một mẩu bánh mì con con
'''
print(str2)
```

```{.python_output}
Hôm nay trời nắng chang chang
mèo con đi học chẳng mang thứ gì
chỉ mang một chiếc bút chì.
Và mang một mẩu bánh mì con con
```

Chúng ta cũng có thể nhập chuỗi với các giá trị xuống dòng bằng kí tự `\n`

```python
str3 = "Ví Dụ xuống dòng \nXuống dòng 2"
print(str3)
```

```{.python_output}
Ví Dụ xuống dòng 
Xuống dòng 2
```

Hoặc chỉ định khoảng cách tab bằng `\t`

```python
str4 = "Ví Dụ tab \t phần 1 \t phần 2"
print(str4)
```

```{.python_output}
Ví Dụ tab 	 phần 1 	 phần 2
```

### Kiểu dữ liệu Boolean

Kiểu dữ liệu Boolean là kiểu dữ liệu chứa một trong hai giá trị
- `True` - có nghĩa là đúng
- `False` - có nghĩa là sai


Ví dụ

```python
is_male = True
print(is_male)
print(type(is_male))
```

```{.python_output}
True
<class 'bool'>
```

### Ép kiểu dữ liệu

Đôi khi chúng ta muốn chuyển đổi kiểu cho biến, chúng ta có thể áp dụng phương pháp ép kiểu trong Python. Để ép kiểu dữ liệu từ kiểu này sang kiểu khác, ta dùng hàm khởi tạo của python

- `int()`: Chuyển đổi một số `float` sang số nguyên, chuỗi kí tự chứa các kí tự số sang số nguyên

- `float()`: Chuyển số `int` sang số thập phân, chuỗi kí tự chưa các kí tự số sang số thập phân

- `str()`: Chuyển các kiểu dữ liệu như số nguyên, số thập phân sang chuỗi


Ví dụ vì vấn đề nhập liệu, mặc dù gần như toàn bộ cột dữ liệu có giá trị float như `1.2`, `1.3`, nhưng người nhập liệu nhập sai dấu `.` thành dấu `,`(ví dụ `1.2` bị nhập thành `1,2`) nên cột đó được nhận diện là `string`. Chúng ta sẽ xử lý string từ `1,2` sang `1.2` bằng phương thức `.replace()` sẽ được đề cập sau. Sau khi xử lý xong, chúng ta sẽ ép kiểu về `float`.

#### Ép kiểu  sang `int`

- Khi chuyển float sang int, kết quả trả về là phần nguyên của số đó.
Ví dụ

Ép kiểu số dương
```python
a = int(2.0)
print(a)
```

```{.python_output}
2
```

```python
a = int(2.5)
print(a)
```

```{.python_output}
2
```

Ép kiểu số âm

```python
a = int(-0.5)
print(a)
```

- Chuyển từ `str` sang `int`

```python
a = "2"
print(int(a))
```

```{.python_output}
2
```

```python
a = "-2"
print(int(a))
```

```{.python_output}
-2
```

Lưu ý khi chuỗi tương ứng với float thì ép kiểu int sẽ báo lỗi

```python
a = "2.5"
print(int(a))
```

```{.python_output}
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[40], line 2
      1 a = "2.5"
----> 2 print(int(a))

ValueError: invalid literal for int() with base 10: '2.5'
```

Ép dữ liệu từ nhị phân sang int, lúc này ở hàm khởi tạo, chúng ta thêm tham số cơ số vào.

```python
# nhị phân
a = b'10101'
print(int(a,2))
```

```{.python_output}
21
```

```python
a = '0B1010'
print(int(a,2))
```

```{.python_output}
10
```

```python
# bát phân
a = b'0o1012'
print(int(a,8))
```

```{.python_output}
522
```

```python
#thập lục phân
a = '0x4A5E'
print(int(a,16))
```

```{.python_output}
19038
```


#### Ép kiểu sang float

- Ép kiểu int sang float

```python
a = 2
print(float(a))
```

```{.python_output}
2.0
```

- Ép kiểu string sang float

```python
a = "2.34"
print(float(a))
```

```{.python_output}
2.34
```
```python
a = "2.0"
print(float(a))
```

```{.python_output}
2.0
```

```python
a = "2"
print(float(a))
```

```{.python_output}
2.0
```

#### Ép kiểu sang string

- ép kiểu int sang str

```python
a = 2
print(str(2))
```

```{.python_output}
2
```

```python
a = 2.5
print(str(a))
```

```{.python_output}
2.5
```