## Bài tập


### TONG_N_SO

Vết hàm tính Tổng từ 1 đến số nguyên dương `n` cho trước

```python
def sum_1_to_n(n):
    ..
    return __
```

Test case:

|Ví dụ|Kết quả|
|:--|:----------|
|`sum_1_to_n(5)`|15|
|`sum_1_to_n(100)`|5050|

**Lưu ý**: không sử dụng công thức `n*(n+1)//2` 

<details><summary><b>Lời giải</b></summary>
<p>

```python
def sum_1_to_n(n):
    answer = 0
    for i in range(1, n+1):
        answer += i
    return answer
```
</p></details>

---

### GIAI_THUA

Viết hàm tìm Giai thừa của một số nguyên dương `n` theo công thức

$n! = 1 \times 2 \times 3 \times .. \times (n-1) \times n$

```python
def findGT(n):
    ...
    return _
```

Test case:

|Ví dụ|Kết quả|
|:--|:----------|
|`findGT(5)`|120|
|`findGT(7)`|5040|

**Lưu ý**: không sử dụng hàm cho sẵn `math.factorial(n)` 

<details><summary><b>Lời giải</b></summary>
<p>

```python
def findGT(n):
    answer = 1
    for i in range(1, n+1):
        answer *= i
    return answer
```

</p></details>
---

### CHIA_CHO_5

**Mô tả**

Viết hàm tìm tất cả các số chia hết cho 5 nhưng không chia hết cho 15 nằm trong đoạn từ `[a, b]` với điều kiện `a>0, b>0`. Kết quả trả về là một danh sách

```python
def find(a, b):
    for i in range(__, __):
        if __:
            ..
            ..
        ..
    return _
```

**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`find(1, 40)`|[5, 10, 20, 25, 35, 40]|
|`find(10, 100)`|[10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def find(a, b):
    answer = []
    for i in range(a, b + 1):
        if (i % 5 == 0) & (i % 3 != 0):
            answer.append(i)
    return answer
```
</p></details>
---

### PARSE_STRING_01

**Mô tả**

Viết một hàm nhận đầu vào là một danh sách các số nguyên dưới dạng chuỗi và đầu ra là một danh sách

```python
def parseString(l):
    ..
    ..
    return
```
**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`parseString("[1, 2, 3, 4, 5]")`|[1, 2, 3, 4, 5]|
|`parseString("[-1, -2]")`|[-1, -2]|
|`parseString("[0]")`|[0]|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def parseString(l):
    items = l.split(',')
    answer = []
    for i in range(len(items)):
        item = items[i].replace('[','').replace(']','').strip() 
        item = int(item)
        answer.append(item)
    return answer
```
</p></details>
---

### ATM

Giả sử bạn đang code thuật toán cho máy ATM với một số tiền vô hạn.
ATM có các đồng tiền với mệnh giá 50 20 10 5 2 1.
Yêu cầu viết thuật toán nhận lệnh số tiền `money` và trả ra số tờ tiền ít nhất


```python
def ATM(money):
    l = [50, 20, 10, 5, 2, 1]
    ..
    ..
    return __
```

**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`ATM(100)`|2 <br> Giải thích: 100 chỉ cần 2 tờ mệnh giá 50"|
|`ATM(121)`|4 <br> Giải thích: 121 = 50 * 2 + 20 * 1 + 1 * 1|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def ATM(money):
    l = [50, 20, 10, 5, 2, 1]
    answer = [0, 0, 0, 0, 0, 0]
    for i in range(len(l)):
        answer[i] = money // l[i]
        money = money % l[i]
    return sum(answer)
```
</p></details>
---

### CONG_THUC_01


Chúng ta hay gặp công thức như minh họa (công thức tính trung bình)

$$ 
\Large \frac{1}{n}\sum_{i=1}^{n}y_i = \frac{1}{n}(y_1 + y_2 + ... + y_n)
$$

Yêu cầu viết một hàm tính arithmetic mean theo công thức trên, Với kí hiệu $\sum_{i=1}^{n}$ là tổng một cái gì đó từ 1 đến n. $y_i$ là giá trị của danh sách $Y$ tại vị trí thứ $i$

Lưu ý: Python index bắt đầu từ 0, nhưng trong toán học sẽ bắt đầu từ 1

```python
def calculate_arithmetic_mean(Y)
    answer = 0
    n = __
    for i in range(__):
        ..
    return answer
```


**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`calculate_arithmetic_mean([1, 2, 3, 4, 5])`|3.0|
|`calculate_arithmetic_mean([2, 4, 6, 8])`|5.0|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def calculate_arithmetic_mean(Y):
    answer = 0
    n = len(Y)
    for i in range(n):
        answer += Y[i]
    answer = answer / n
    return answer
```
<p></details>

--- 

### CONG_THUC_02


Một công thức tính trung bình khác  đó là trung bình hình học

$$ 
\Large \left(\prod _{i=1}^{n}y_{i}\right)^{\frac {1}{n}}={\sqrt[{n}]{y_{1} \times y_{2} \times \cdots \times y_{n}}}
$$ 

Yêu cầu viết một hàm tính geometric mean theo công thức trên.

Lưu ý: Python index bắt đầu từ 0, nhưng trong toán học sẽ bắt đầu từ 1

Để tính lũy thừa của 1 số ta dùng hàm `pow()`.

- Ví dụ để tính lũy thừa 3 của 2 ta dùng `pow(2, 3)`

- Ví dụ để tính căn bậc 3 của 2 ta dùng `pow(2, 1/3)`

```python
def calculate_geometric_mean(Y):
    answer = 1
    n = __
    for i in range(__):
        ..
    return answer
```


**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`calculate_geometric_mean([1, 2, 3, 4, 5])`|2.605171084697352|
|`calculate_geometric_mean([2, 4, 6, 8])`|4.426727678801286|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def calculate_geometric_mean(Y):
    answer = 1
    n = len(Y)
    for i in range(n):
        answer *= Y[i]
    answer = math.pow(answer, 1/n)
    return answer
```
<p></details>

---

### UCLN

Viết hàm tìm Ước chung lớn nhất của hai số  nguyên dương `a`, `b`


```python
def findUCLN(a, b):
    ..
    return __
```


Test case:

|Ví dụ|Kết quả|
|:--|:----------|
|`findUCLN(50, 20)`|10|
|`findUCLN(60, 520)`|20|

**Lưu ý**: không sử dụng hàm cho sẵn `math.gcd(a, b)` 


<details><summary><b>Lời giải</b></summary>
<p>

```python
def findUCLN(a, b):
    while b != 0:
        temp = b
        b = a % b
        a = temp
        # a, b = b, a % b
    return a
```
</p></details>
---

### BCNN

Viết hàm tìm Bội chung nhỏ nhất của hai số nguyên dương `a`, `b`

```python
def findBCNN(a, b):
    ..
    ..
    return __
```

Test case:

|Ví dụ|Kết quả|
|:--|:----------|
|`findBCNN(8, 6)`|24|
|`findBCNN(30, 520)`|1560|

**Lưu ý**: không sử dụng hàm cho sẵn `math.lcm(a, b)` 

<details><summary><b>Lời giải</b></summary>
<p>

```python
def findBCNN(a, b):
    answer = a * b // findUCLN(a, b)
    return answer
```
</p></details>

---

### RUT_GON_DA_THUC_01

Viết một hàm nhận một đa thức  và trả ra đa thức rút gọn sắp xếp theo trình tự giảm dần của bậc.
`^` là kí hiệu cho dấu lũy thừa

Ràng buộc:

- Các hệ số không âm, giữa các hệ số và `x` sẽ là dấu `*` đại diện cho dấu nhân
- phép tính giữa các đơn thức là phép `+`


```python
def rut_gon_da_thuc(dathuc):
    return __
```

**Test case**

|Ví dụ|Kết quả|
|:--|:----------|
|`rut_gon_da_thuc("3*x^2 + 2*x + 2*x^2")`|"5\*x^2 + 2\*x"|
|`rut_gon_da_thuc("2*x + 2*x^2 + 5*x + 3")`|"2\*x^2 + 7\*x + 3"|
|`rut_gon_da_thuc("3*x^5 + 2*x + 2*x^5 + 4*x")`|"5\*x^5 + 6\*x"|

<details><summary><b>Lời giải</b></summary>
<p>

```python
def rut_gon_da_thuc(da_thuc):
    # Tách biệt các hạng tử
    hts = da_thuc.split(" + ")
    print(hts)
    # Tạo một từ điển để lưu trữ số lượng và hạng tử
    thong_ke = {}
    
    for ht in hts:
        print(ht)
        if '*' not in ht:
            he_so, bac = ht, 0
        else:
            he_so, bac = ht.split("*x")
            print(he_so, bac)
            if "^" in bac:
                bac = int(bac.split("^")[1])
            else:
                bac = 1
        # Cập nhật số lượng và hạng tử trong từ điển
        if bac in thong_ke:
            thong_ke[bac] += int(he_so)
        else:
            thong_ke[bac] = int(he_so)
    
    print(thong_ke)
    # Tạo đa thức đã rút gọn
    da_thuc_rut_gon = ""
    for bac, he_so in sorted(thong_ke.items(), reverse=True):
        if he_so != 0:
            if bac >=2 :
                da_thuc_rut_gon += f"{he_so}*x^{bac} + "
            elif bac == 1:
                da_thuc_rut_gon += f"{he_so}*x + "
            else:
                da_thuc_rut_gon += str(he_so)
    
    # Loại bỏ dấu + cuối cùng
    da_thuc_rut_gon = da_thuc_rut_gon.rstrip(" + ")
    
    return da_thuc_rut_gon
```
</p></details>
---